exclude: 'cookiecutter.*'
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
  - repo: local
    hooks:
      - id: black
        name: black
        description: This hook runs black formatter
        entry: .venv/bin/black .
        language: system
        types:
          - python
      - id: ruff
        name: ruff
        description: This hook runs ruff linter
        entry: .venv/bin/ruff check --fix .
        language: system
        types:
          - python
