# This is an example configuration file for the integration service.
# Please copy this file to config.yaml file in the integration folder and edit it to your needs.

port:
  clientId: "{{ from env OCEAN__PORT__CLIENT_ID }}" # Can be loaded using environment variable: PORT_CLIENT_ID or OCEAN__PORT__CLIENT_ID
  clientSecret: "{{ from env OCEAN__PORT__CLIENT_SECRET }}" # Can be loaded using environment variable: PORT_CLIENT_SECRET or OCEAN__PORT__CLIENT_SECRET
# The event listener to use for the integration service.
eventListener:
  type: POLLING
integration:
  # The identifier of this integration instance.
  # Can be loaded using environment variable: INTEGRATION_IDENTIFIER or OCEAN__INTEGRATION__IDENTIFIER
  identifier: "{{ from env OCEAN__INTEGRATION__IDENTIFIER }}"
  # These two should match the values in the .port/spec.yaml file
  type: "My Integration type (Gitlab, Jira, etc.)"
  config:
    github_token: "{{ from env OCEAN__GITHUB_TOKEN }}"
    github_org: "{{ from env OCEAN__GITHUB_ORG }}"
    github_repo: "{{ from env OCEAN__GITHUB_REPO }}"